syntax = "proto3";

package distributedkv.raft.v1;

option go_package = "github.com/pranavbhole123/distributed_kv_store/internal/transport/proto;raftpb";

service RaftService {
  rpc RequestVote(RequestVoteRequest) returns (RequestVoteResponse);
  rpc AppendEntries(AppendEntriesRequest) returns (AppendEntriesResponse);
}

message RequestVoteRequest {
  uint64 term = 1;
  int32 candidate_id = 2;
  uint64 last_log_index = 3;
  uint64 last_log_term = 4;
}

message RequestVoteResponse {
  uint64 term = 1;
  bool vote_granted = 2;
}

message AppendEntriesRequest {
  uint64 term = 1;
  int32 leader_id = 2;
  uint64 prev_log_index = 3;
  uint64 prev_log_term = 4;
  repeated LogEntry entries = 5;
  uint64 leader_commit = 6;
}

message AppendEntriesResponse {
  uint64 term = 1;
  bool success = 2;
}

enum Operation {
  OPERATION_UNSPECIFIED = 0;
  OPERATION_SET = 1;
  OPERATION_DELETE = 2;
}

message LogEntry {
  uint64 index = 1;
  uint64 term = 2;
  Operation operation = 3;
  string key = 4;
  string value = 5;
}
